### ISSUE TITLE
When creating new pipeline, services do not show up

### ISSUE THREAD

**Issue by asjongers** [big-data-europe/ember-swarm-ui-engine#2]
They do show up after refresh but this shouldn't be needed.

**Comment by asjongers** [comment]
@fr0gs You fixed it already from what I've heard? Can you confirm?

**Comment by fr0gs** [comment]
@asjongers Yes, I will push changes in app-integrator-ui and app-bdi-ide.

Fixed in commit: [https://github.com/big-data-europe/ember-swarm-ui-engine/commit/94150342a2ab59023297b913196d44734c591823](https://github.com/big-data-europe/ember-swarm-ui-engine/commit/94150342a2ab59023297b913196d44734c591823)
